### ISSUE TITLE
[BUG] Victory Parade markers are rotated backwards by init script

### ISSUE THREAD

**Issue by HazelrahBL** [HazelrahBL/EraOfTribesTTS#12]
**Describe the bug**
Because I'm an idiot, I updated the script to rotate the Victory Parade markers the wrong direction. It's a chariot, so the high side of the vehicle is the front!

**To Reproduce**
1. Setup a game
2. See that the Victory Parade is facing the wrong way! (do'h!)

**Expected behavior**
They should be facing the correct way after setup

**Comment by cyrilepinat** [comment]
I take this one
